version: 2.1 # circle ci process engine version

orbs:
  python: circleci/python@2.0.3

jobs:
  run-and-test:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    executor: python/default # use the default executor defined within the orb
    
    steps:
      - checkout
      - run:
          name: Install Pytest module
          command: pip install pytest numpy
      - run:
          name: Execute sparse_recommender file
          command: python sparse_recommender.py
      - run:
          name: Test Sparse Recommender
          command: pytest test_sparse_recommender.py

  build-and-push:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Docker build
          command: docker build --no-cache -t $DOCKERHUB_USERNAME/sparse_matrix_recommender:${CIRCLE_SHA1} .
      - run:
          name: Authenticate with Docker Hub
          command: echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Push Docker Image to Docker Hub
          command: docker push $DOCKERHUB_USERNAME/sparse_matrix_recommender:${CIRCLE_SHA1}


workflows:
  test-run-workflow:
    jobs:
      - run-and-test:
          filters:
            branches:
              only: master # only deploy when on master
      - build-and-push:
          requires:
            - run-and-test
          filters:
            branches:
              only: master # only deploy when on master
